services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: build
    container_name: c-frontend
    expose:
      - "5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    networks:
      - services-net

  nginx:
    image: nginx:latest
    container_name: c-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - services-net

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: c-backend
    ports:
      - "81:81"
    expose:
      - "81"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    networks:
      - services-net
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: c-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - services-net

networks:
  services-net:
    driver: bridge

volumes:
  mysql_data:
